- name: Setup Prometheus and Grafana
  hosts: uniops
  become: yes

  vars:
    prometheus_version: "2.51.2"
    grafana_version: "10.3.3"

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: [wget, tar, adduser, libfontconfig1, gnupg2, software-properties-common]
        state: present

    # -----------------------------
    # PROMETHEUS
    # -----------------------------
    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Copy Prometheus binaries
      copy:
        remote_src: yes
        src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: "0755"
      loop:
        - prometheus
        - promtool

    - name: Create Prometheus config directory
      file:
        path: /etc/prometheus
        state: directory

    - name: Copy Prometheus config file
      copy:
        src: files/prometheus.yml
        dest: /etc/prometheus/prometheus.yml

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus \
            --web.listen-address=:9090
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started

    # -----------------------------
    # GRAFANA
    # -----------------------------
    - name: Add Grafana APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Start and enable Grafana
      systemd:
        name: grafana-server
        enabled: yes
        state: started
